name: Continuous Delivery

on: 
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.1.7

      - name: Delivery
        uses: actions/upload-artifact@v4.4.0
        with:
          name: projeto-password-generator
          path: /home/runner/work/Password-Generator/Password-Generator
      
  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: projeto-password-generator
      
      - name: Display structure of downloaded files
        run: ls -R

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Build and push
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          push: false
          tags: user/app:latest