name: Continuous Delivery

on:
  push:
    branches: [ "main" ]

jobs:
  deliver:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
    - uses: actions/checkout@v4

    - name: Delivery
    - uses: actions/upload-artifact@v4
      with:
        name: projeto-password-generator
        path: /home/gustavomedeiros/Programming/Password-Generator/
    