name: Discord

on:
  - push 

jobs:
  discord:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4.1.7
      - name: Send Discord notification
        uses: stegzilla/discord-notify@v2
        with:
            webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
            title: New PR opened
            message: "**${{ github.event.push.title }}**\n**Creator:** ${{ github.event.push.user.login }}\n${{ github.event.push.html_url }}"
            include_image: true
            avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
            username: GitHub PR Notifier
